@baseUrl=http://localhost:8080

GET {{baseUrl}}/shopType/list
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMUBxcS5jb20iLCJpZCI6MTAxMSwiZXhwIjoxNzU2MDUyMzczLCJsZXZlbCI6IjAiLCJpYXQiOjE3NTYwMjcxNzN9.NQ8g4RzkN-1ZKBdFf-br46OWs0O5WJjy2n50C2I2j-zXwSrSI7NTrxCnRMt0Ob0jpHHNefG4QfV-GgOUbru1Z2cd4PjB3pdaWKxS4XYqIdFh-4oD_C7CV9fEokbtGuq3p2LY0hJcYN02IcGbllk9_eF1vTErXNQ3DgX8JIlLwDS_XEe6EdOGWW3sKwxroH3djtUDBylyhg76F8WD3bTIom_om19TficOXREtRm2d4YyT0ygMsDuymdRypkOoVKDNmTxVLntH5gwb_dithRkJ0EO9DPMDteIIsN5x3IVzN7b_Vwtu2bkXhMDlbQvNnekpfxs5UGR2EfvyyIcYSXREBg
