server:
  port: 8080
spring:
  application:
    name: critiq
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/critiq
    username: root
    password: root
  data:
    redis:
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 6
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mail:
    host: smtp.qq.com
    username: no.msg.reply@qq.com
    password:
    properties:
      smtp:
        ssl:
          enabled: true
    ssl:
      enabled: true
  cloud:
    stream:
      function:
        bindings:
          voucherOrder-in-0: queue.orders
    aws:
      s3:
        endpoint: http://localhost:9000
        region: eu-west-2
        path-style-access-enabled: true
      credentials:
        access-key: minioadmin
        secret-key: minioadmin
  rabbitmq:
    host: localhost
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1
  main:
    allow-circular-references: true
mybatis-plus:
  type-aliases-package: me.critiq.backend.domain.entity # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  key:
    private: classpath:key/private_key.pem
    public: classpath:key/public_key.pem
logging:
  level:
    root: info